#!/usr/bin/env bash
set -euo pipefail

export SMOKE_GPUS="${SMOKE_GPUS:-4}"
export SMOKE_PROBLEM_BATCH_SIZE="${SMOKE_PROBLEM_BATCH_SIZE:-32}"
if [[ ! "${SMOKE_GPUS}" =~ ^[1-9][0-9]*$ ]] || \
  [[ ! "${SMOKE_PROBLEM_BATCH_SIZE}" =~ ^[1-9][0-9]*$ ]]; then
  echo "SMOKE_GPUS and SMOKE_PROBLEM_BATCH_SIZE must be positive integers." >&2
  exit 2
fi
if (( SMOKE_PROBLEM_BATCH_SIZE % SMOKE_GPUS != 0 )); then
  echo "SMOKE_PROBLEM_BATCH_SIZE must be divisible by SMOKE_GPUS." >&2
  exit 2
fi
export SMOKE_PROBLEM_MICRO_BATCH_SIZE="${SMOKE_PROBLEM_MICRO_BATCH_SIZE:-${SMOKE_PROBLEM_BATCH_SIZE}}"
if [[ ! "${SMOKE_PROBLEM_MICRO_BATCH_SIZE}" =~ ^[1-9][0-9]*$ ]] || \
  (( SMOKE_PROBLEM_BATCH_SIZE % SMOKE_PROBLEM_MICRO_BATCH_SIZE != 0 || \
     SMOKE_PROBLEM_MICRO_BATCH_SIZE % SMOKE_GPUS != 0 )); then
  echo "SMOKE_PROBLEM_MICRO_BATCH_SIZE must divide the problem batch and be divisible by SMOKE_GPUS." >&2
  exit 2
fi
export SMOKE_ROLLOUT_PROBLEM_BATCH_SIZE="${SMOKE_ROLLOUT_PROBLEM_BATCH_SIZE:-${SMOKE_PROBLEM_BATCH_SIZE}}"
if [[ ! "${SMOKE_ROLLOUT_PROBLEM_BATCH_SIZE}" =~ ^[1-9][0-9]*$ ]] || \
  (( SMOKE_PROBLEM_BATCH_SIZE % SMOKE_ROLLOUT_PROBLEM_BATCH_SIZE != 0 || \
     SMOKE_ROLLOUT_PROBLEM_BATCH_SIZE % SMOKE_GPUS != 0 )); then
  echo "SMOKE_ROLLOUT_PROBLEM_BATCH_SIZE must divide the problem batch and be divisible by SMOKE_GPUS." >&2
  exit 2
fi
local_rollout_problem_batch_size=$((SMOKE_ROLLOUT_PROBLEM_BATCH_SIZE / SMOKE_GPUS))

export META_RLVR_RUN_LABEL="problem-batch-${SMOKE_PROBLEM_BATCH_SIZE}"
export SMOKE_ROLLOUT_BACKEND=vllm
export SMOKE_LOG_ROLLOUTS=1
export SMOKE_MAX_STEPS="${SMOKE_MAX_STEPS:-1}"
export SMOKE_SAVE_STEPS="${SMOKE_SAVE_STEPS:-1}"
export SMOKE_MAX_NEW_TOKENS="${SMOKE_MAX_NEW_TOKENS:-128}"
export SMOKE_SUPPORT_GROUP_SIZE="${SMOKE_SUPPORT_GROUP_SIZE:-2}"
export SMOKE_QUERY_GROUP_SIZE="${SMOKE_QUERY_GROUP_SIZE:-2}"
export SMOKE_INNER_ITERATIONS="${SMOKE_INNER_ITERATIONS:-1}"
export SMOKE_OUTER_ITERATIONS="${SMOKE_OUTER_ITERATIONS:-1}"
export SMOKE_GENERATION_MICRO_BATCH_SIZE="${SMOKE_GENERATION_MICRO_BATCH_SIZE:-2}"
export SMOKE_POLICY_MICRO_BATCH_SIZE="${SMOKE_POLICY_MICRO_BATCH_SIZE:-4}"
export SMOKE_CONFIDENCE_MICRO_BATCH_SIZE="${SMOKE_CONFIDENCE_MICRO_BATCH_SIZE:-4}"
export SMOKE_POLICY_MAX_TOKENS_PER_MICRO_BATCH="${SMOKE_POLICY_MAX_TOKENS_PER_MICRO_BATCH:-2048}"
export SMOKE_CONFIDENCE_MAX_TOKENS_PER_MICRO_BATCH="${SMOKE_CONFIDENCE_MAX_TOKENS_PER_MICRO_BATCH:-2048}"
export VLLM_GPU_MEMORY_UTILIZATION="${VLLM_GPU_MEMORY_UTILIZATION:-0.30}"
export VLLM_MAX_NUM_SEQS="${VLLM_MAX_NUM_SEQS:-64}"
export VLLM_MAX_LORAS="${VLLM_MAX_LORAS:-${local_rollout_problem_batch_size}}"
export VLLM_MAX_CPU_LORAS="${VLLM_MAX_CPU_LORAS:-${VLLM_MAX_LORAS}}"
export NCCL_DEBUG="${NCCL_DEBUG:-WARN}"
export SLURM_TIME="${SLURM_TIME:-02:00:00}"

exec bash scripts/submit_smoke_test.sh
