#!/usr/bin/env bash
set -euo pipefail

export SMOKE_GPUS=1
export SMOKE_ROLLOUT_BACKEND=vllm
export SMOKE_ROLLOUT_ONLY=1
export SMOKE_LOG_ROLLOUTS=1
export META_RLVR_RUN_LABEL=vllm-lifecycle
export SLURM_TIME="${SLURM_TIME:-00:30:00}"
export SMOKE_MAX_STEPS=1
export SMOKE_SAVE_STEPS=1
export SMOKE_VALIDATION_PROBLEMS=1
export SMOKE_SUPPORT_GROUP_SIZE=2
export SMOKE_QUERY_GROUP_SIZE=2
export SMOKE_MAX_NEW_TOKENS=32
export SMOKE_INNER_ITERATIONS=1
export SMOKE_OUTER_ITERATIONS=1
export VLLM_GPU_MEMORY_UTILIZATION="${VLLM_GPU_MEMORY_UTILIZATION:-0.30}"
export VLLM_MAX_NUM_SEQS=2
export VLLM_MAX_LORAS=1
export VLLM_MAX_CPU_LORAS=1
export VLLM_STARTUP_TIMEOUT="${VLLM_STARTUP_TIMEOUT:-300}"
export VLLM_CONTROL_TIMEOUT="${VLLM_CONTROL_TIMEOUT:-120}"
export VLLM_REQUEST_TIMEOUT="${VLLM_REQUEST_TIMEOUT:-300}"

exec bash scripts/submit_smoke_test.sh
