#!/usr/bin/env bash
set -euo pipefail

# Complete, self-contained configuration for the 1536-problem meta-only run.
unset PYTORCH_CUDA_ALLOC_CONF
unset PYTORCH_ALLOC_CONF

export META_RLVR_PROJECT_DIR="${HOME}/meta-rlvr"
export META_RLVR_CONDA_ENV="verl"
export META_RLVR_MODEL_PATH="/data/user/zhongal/.cache/qwen2.5-math-7b-local"
export META_RLVR_TRAIN_PARQUET="/data/user/zhongal/data/reschedule/DAPO-Math-17k.filtered.seed42.sample1536.parquet"
export META_RLVR_VALIDATION_PARQUET="/data/user/zhongal/data/reschedule/aime24.parquet"
export META_RLVR_OUTPUT_DIR="${META_RLVR_PROJECT_DIR}/outputs"
export META_RLVR_RUN_LABEL="tiny-meta-only-b512"

export SMOKE_GPUS=8
export SMOKE_MAX_STEPS=3
export SMOKE_SAVE_STEPS=1
export SMOKE_EVAL_STEPS=0
export SMOKE_PROBLEM_BATCH_SIZE=512
export SMOKE_PROBLEM_MICRO_BATCH_SIZE=16
export SMOKE_ROLLOUT_PROBLEM_BATCH_SIZE=64
export SMOKE_SUPPORT_GROUP_SIZE=16
export SMOKE_QUERY_GROUP_SIZE=16
export SMOKE_VALIDATION_SUPPORT_GROUP_SIZE=16
export SMOKE_VALIDATION_QUERY_GROUP_SIZE=32
export SMOKE_VALIDATION_PROBLEMS=30
export SMOKE_INNER_ITERATIONS=2
export SMOKE_OUTER_ITERATIONS=2
export SMOKE_FIRST_ORDER_VJP_FORWARD_BATCH_SIZE=1
export SMOKE_META_COEFFICIENT=1.0
export SMOKE_BCE_COEFFICIENT=0.0
export SMOKE_RANKING_COEFFICIENT=0.0
export SMOKE_LOG_COMPONENT_GRADIENT_NORMS=0
export SMOKE_OFFLOAD_CONFIDENCE_OPTIMIZER=0
export SMOKE_DEFER_CONFIDENCE_GRADIENT_SYNC=0

export SMOKE_MAX_NEW_TOKENS=3072
export SMOKE_GENERATION_MICRO_BATCH_SIZE=16
export SMOKE_POLICY_MICRO_BATCH_SIZE=16
export SMOKE_CONFIDENCE_MICRO_BATCH_SIZE=16
export SMOKE_POLICY_MAX_TOKENS_PER_MICRO_BATCH=4096
export SMOKE_CONFIDENCE_MAX_TOKENS_PER_MICRO_BATCH=4096
export SMOKE_LOG_ROLLOUTS=1
export SMOKE_ROLLOUT_BACKEND=vllm
export SMOKE_LORA_RANK=8

export VLLM_GPU_MEMORY_UTILIZATION=0.30
export VLLM_MAX_MODEL_LEN=4096
export VLLM_MAX_NUM_SEQS=64
export VLLM_MAX_LORAS=8
export VLLM_MAX_CPU_LORAS=8

export SLURM_PARTITION=acd_u
export SLURM_GRES=gpu:8
export SLURM_CPUS_PER_TASK=64
export SLURM_MEM=400G
export SLURM_TIME=08:00:00
export SLURM_EXCLUDE=ACD1-1
export NCCL_DEBUG=WARN
export TQDM_MININTERVAL=5

cd "${META_RLVR_PROJECT_DIR}"
exec bash scripts/submit_meta_meaningful_test.sh
